# Name of the workflow, will be displayed in the GitHub Actions tab
name: Deploy to Google Cloud Run

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [main]

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-west1 # The region of your Artifact Registry
  SERVICE_NAME: discord-assistant-chatbot # The name of your Cloud Run service
  IMAGE_NAME: assistant-chatbot-ts # The name of the Docker image

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. Set up the gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. Configure Docker to use gcloud as a credential helper
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # 5. Build and push the Docker image to Google Artifact Registry
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 6. Deploy the new image to Google Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.GAR_LOCATION }}
          # Use the image we just built and pushed
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          # Pass your bot's secrets to Cloud Run as environment variables
          env_vars: |
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }}
            GOOGLE_CREDENTIALS_JSON=${{ secrets.GOOGLE_CREDENTIALS_JSON }}
            NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}
            OPEN_ROUTER_API_KEY=${{ secrets.OPEN_ROUTER_API_KEY }}
