# .github/workflows/deploy.yml
name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railwaydev/cli

      # 2. Deploy to Railway
      # Railway automatically detects your Dockerfile and builds/deploys it.
      # It will pick up the 'production' stage since it's the last one defined.
      - name: Deploy Application to Railway
        run: railway deploy --commit-hash ${{ github.sha }} --detach --service assistant-chatbot-ts
        env:
          # Railway API Token (required for deployment)
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          # Pass your application environment variables.
          # Railway will inject these into your running container.
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}

          NODE_ENV: production